name: Periodic Health Check
on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-20.04
    steps:
      - name: Periodic Health Check
        uses: jtalk/url-health-check-action@v3
        if: github.event.schedule != '30 5 * * 1,3'
        with:
          url: https://blogapp-ix7a.onrender.com
          follow-redirect: false 
          max-attempts: 2
          retry-delay: 5s 
          retry-all: false